version: "3.9"

services:
  tri-lari-scoring:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    platform: linux/amd64
    ports:
      - "8787:8787"
    environment:
      PASSWORD: rstudio
    volumes:
      - ./:/home/rstudio/workspace