---
title: "TRI/LARI Analyses"
author: "Sirish Shrestha"
date: "2023-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("./src/init.R")

```



```{r}

BMK2018_A <- load_data(source=sprintf("%s/data/BMK2018_A.RData", getwd()), raters=raters)

BMK2018_B <- load_data(source=sprintf("%s/data/BMK2018_B.RData", getwd()), raters=raters)


```



```{r decisiveness, echo=FALSE}

#  1. Decisiveness
decisive <- get_variables_for_analyses(df = BMK2018_A, columns = c("BMK_S1_34", "BMK_S1_73", "BMK_S1_77"), factor_name = "decisive")



data_A <- list(BMK2018_A, "Normative") %>% setNames(c("data", "sample_name"))
data_B <- list(BMK2018_B, "Cross-validation") %>% setNames(c("data", "sample_name"))


## Loop through the normative and cross-validation samples to create the analyses. For each loop, the code will process the data and get it ready for the lavaan analyses. 
sapply(list(data_A, data_B), function(x) {
  
  ## data processing
  render_data_processing(data=x$data, 
                        sample_name=x$sample_name,
                        raters=decisive$raters,
                        factor_name=decisive$factor_name,
                        research_cols=decisive$research_cols,
                        grouping_cols=decisive$grouping_cols,
                        required_cols=decisive$required_cols,
                        competency_cols=decisive$competency_cols,
                        competency_item_cols=decisive$competency_item_cols)
  
  
  
  ## lavan analyses for decisiveness
  render_lavaan_analyses(
    show_model=TRUE,
    factor_name=decisive$factor_name,
    sample_name=x$sample_name,
    regex_pattern=decisive$regex_pattern,
    outcome_raters=decisive$outcome_raters,
    outcome_colname=decisive$outcome_colname,
    factor_weights_cols=decisive$factor_weights_cols,
    rowmeans_columns_list=decisive$rowmeans_columns_list,
    competency_cols_names=decisive$competency_cols_pattern,
    column_pattern_for_analyses=decisive$column_pattern_for_analyses,
    factor_weights_competency_cols=decisive$factor_weights_competency_cols,
    columns_to_remove_missing_values=decisive$columns_to_remove_missing_values,
    competency_cols_with_factor_weights=decisive$competency_cols_with_factor_weights)

})

```




```{r being-a-quick-study, echo=FALSE}

# 2. Being a quick study

quick <- get_variables_for_analyses(df = BMK2018_A, columns = c("BMK_S1_11", "BMK_S1_30", "BMK_S1_45"), factor_name = "quick")


data_A <- list(BMK2018_A, "Normative") %>% setNames(c("data", "sample_name"))
data_B <- list(BMK2018_B, "Cross-validation") %>% setNames(c("data", "sample_name"))


## Loop through the normative and cross-validation samples to create the analyses. For each loop, the code will process the data and get it ready for the lavaan analyses. 
sapply(list(data_A, data_B), function(x) {
  
  ## data processing
  render_data_processing(data=x$data, 
                        sample_name=x$sample_name,
                        raters=quick$raters,
                        factor_name=quick$factor_name,
                        research_cols=quick$research_cols,
                        grouping_cols=quick$grouping_cols,
                        required_cols=quick$required_cols,
                        competency_cols=quick$competency_cols,
                        competency_item_cols=quick$competency_item_cols)
  
  
  
  ## lavan analyses for decisiveness
  render_lavaan_analyses(
    show_model=TRUE,
    factor_name=quick$factor_name,
    sample_name=x$sample_name,
    regex_pattern=quick$regex_pattern,
    outcome_raters=quick$outcome_raters,
    outcome_colname=quick$outcome_colname,
    factor_weights_cols=quick$factor_weights_cols,
    rowmeans_columns_list=quick$rowmeans_columns_list,
    competency_cols_names=quick$competency_cols_pattern,
    column_pattern_for_analyses=quick$column_pattern_for_analyses,
    factor_weights_competency_cols=quick$factor_weights_competency_cols,
    columns_to_remove_missing_values=quick$columns_to_remove_missing_values,
    competency_cols_with_factor_weights=quick$competency_cols_with_factor_weights)

})

```




```{r strategic-perspective, echo=FALSE}

# 3. Strategic perspective

strategic <- get_variables_for_analyses(df = BMK2018_A, columns = c("BMK_S1_1", "BMK_S1_6", "BMK_S1_7", "BMK_S1_10", "BMK_S1_13", "BMK_S1_19", "BMK_S1_24", "BMK_S1_28"), factor_name = "strategic")



data_A <- list(BMK2018_A, "Normative") %>% setNames(c("data", "sample_name"))
data_B <- list(BMK2018_B, "Cross-validation") %>% setNames(c("data", "sample_name"))


## Loop through the normative and cross-validation samples to create the analyses. For each loop, the code will process the data and get it ready for the lavaan analyses. 
sapply(list(data_A, data_B), function(x) {
  
  ## data processing
  render_data_processing(data=x$data, 
                        sample_name=x$sample_name,
                        raters=strategic$raters,
                        factor_name=strategic$factor_name,
                        research_cols=strategic$research_cols,
                        grouping_cols=strategic$grouping_cols,
                        required_cols=strategic$required_cols,
                        competency_cols=strategic$competency_cols,
                        competency_item_cols=strategic$competency_item_cols)
  
  
  
  ## lavan analyses for decisiveness
  render_lavaan_analyses(
    show_model=TRUE,
    factor_name=strategic$factor_name,
    sample_name=x$sample_name,
    regex_pattern=strategic$regex_pattern,
    outcome_raters=strategic$outcome_raters,
    outcome_colname=strategic$outcome_colname,
    factor_weights_cols=strategic$factor_weights_cols,
    rowmeans_columns_list=strategic$rowmeans_columns_list,
    competency_cols_names=strategic$competency_cols_pattern,
    column_pattern_for_analyses=strategic$column_pattern_for_analyses,
    factor_weights_competency_cols=strategic$factor_weights_competency_cols,
    columns_to_remove_missing_values=strategic$columns_to_remove_missing_values,
    competency_cols_with_factor_weights=strategic$competency_cols_with_factor_weights)

})

```





```{r leading-employees, echo=FALSE}

# 4. Leading employees

leading <- get_variables_for_analyses(df = BMK2018_A, columns = c("BMK_S1_12", "BMK_S1_15", "BMK_S1_17", "BMK_S1_18", "BMK_S1_26", "BMK_S1_47", "BMK_S1_68", "BMK_S1_88", "BMK_S1_39", "BMK_S1_43", "BMK_S1_52", "BMK_S1_37", "BMK_S1_38"), factor_name = "leading")



data_A <- list(BMK2018_A, "Normative") %>% setNames(c("data", "sample_name"))
data_B <- list(BMK2018_B, "Cross-validation") %>% setNames(c("data", "sample_name"))


## Loop through the normative and cross-validation samples to create the analyses. For each loop, the code will process the data and get it ready for the lavaan analyses. 
sapply(list(data_A, data_B), function(x) {
  
  ## data processing
  render_data_processing(data=x$data, 
                        sample_name=x$sample_name,
                        raters=leading$raters,
                        factor_name=leading$factor_name,
                        research_cols=leading$research_cols,
                        grouping_cols=leading$grouping_cols,
                        required_cols=leading$required_cols,
                        competency_cols=leading$competency_cols,
                        competency_item_cols=leading$competency_item_cols)
  
  
  
  ## lavan analyses for decisiveness
  render_lavaan_analyses(
    show_model=TRUE,
    factor_name=leading$factor_name,
    sample_name=x$sample_name,
    regex_pattern=leading$regex_pattern,
    outcome_raters=leading$outcome_raters,
    outcome_colname=leading$outcome_colname,
    factor_weights_cols=leading$factor_weights_cols,
    rowmeans_columns_list=leading$rowmeans_columns_list,
    competency_cols_names=leading$competency_cols_pattern,
    column_pattern_for_analyses=leading$column_pattern_for_analyses,
    factor_weights_competency_cols=leading$factor_weights_competency_cols,
    columns_to_remove_missing_values=leading$columns_to_remove_missing_values,
    competency_cols_with_factor_weights=leading$competency_cols_with_factor_weights)

})

```





```{r respect-for-differences, echo=FALSE}

# 5. Respect for differences

respect <- get_variables_for_analyses(df = BMK2018_A, columns = c("BMK_S1_12", "BMK_S1_15", "BMK_S1_17", "BMK_S1_18", "BMK_S1_26", "BMK_S1_47", "BMK_S1_68", "BMK_S1_88", "BMK_S1_39", "BMK_S1_43", "BMK_S1_52", "BMK_S1_37", "BMK_S1_38"), factor_name = "respect")



data_A <- list(BMK2018_A, "Normative") %>% setNames(c("data", "sample_name"))
data_B <- list(BMK2018_B, "Cross-validation") %>% setNames(c("data", "sample_name"))


## Loop through the normative and cross-validation samples to create the analyses. For each loop, the code will process the data and get it ready for the lavaan analyses. 
sapply(list(data_A, data_B), function(x) {
  
  ## data processing
  render_data_processing(data=x$data, 
                        sample_name=x$sample_name,
                        raters=respect$raters,
                        factor_name=respect$factor_name,
                        research_cols=respect$research_cols,
                        grouping_cols=respect$grouping_cols,
                        required_cols=respect$required_cols,
                        competency_cols=respect$competency_cols,
                        competency_item_cols=respect$competency_item_cols)
  
  
  
  ## lavan analyses for decisiveness
  render_lavaan_analyses(
    show_model=TRUE,
    factor_name=respect$factor_name,
    sample_name=x$sample_name,
    regex_pattern=respect$regex_pattern,
    outcome_raters=respect$outcome_raters,
    outcome_colname=respect$outcome_colname,
    factor_weights_cols=respect$factor_weights_cols,
    rowmeans_columns_list=respect$rowmeans_columns_list,
    competency_cols_names=respect$competency_cols_pattern,
    column_pattern_for_analyses=respect$column_pattern_for_analyses,
    factor_weights_competency_cols=respect$factor_weights_competency_cols,
    columns_to_remove_missing_values=respect$columns_to_remove_missing_values,
    competency_cols_with_factor_weights=respect$competency_cols_with_factor_weights)

})

```





```{r compassion-sensitivity, echo=FALSE}

# 6. Compassion & Sensitivity

compassion <- get_variables_for_analyses(df = BMK2018_A, columns = c("BMK_S1_12", "BMK_S1_15", "BMK_S1_17", "BMK_S1_18", "BMK_S1_26", "BMK_S1_47", "BMK_S1_68", "BMK_S1_88", "BMK_S1_39", "BMK_S1_43", "BMK_S1_52", "BMK_S1_37", "BMK_S1_38"), factor_name = "compassion")



data_A <- list(BMK2018_A, "Normative") %>% setNames(c("data", "sample_name"))
data_B <- list(BMK2018_B, "Cross-validation") %>% setNames(c("data", "sample_name"))


## Loop through the normative and cross-validation samples to create the analyses. For each loop, the code will process the data and get it ready for the lavaan analyses. 
sapply(list(data_A, data_B), function(x) {
  
  ## data processing
  render_data_processing(data=x$data, 
                        sample_name=x$sample_name,
                        raters=compassion$raters,
                        factor_name=compassion$factor_name,
                        research_cols=compassion$research_cols,
                        grouping_cols=compassion$grouping_cols,
                        required_cols=compassion$required_cols,
                        competency_cols=compassion$competency_cols,
                        competency_item_cols=compassion$competency_item_cols)
  
  
  
  ## lavan analyses for decisiveness
  render_lavaan_analyses(
    show_model=TRUE,
    factor_name=compassion$factor_name,
    sample_name=x$sample_name,
    regex_pattern=compassion$regex_pattern,
    outcome_raters=compassion$outcome_raters,
    outcome_colname=compassion$outcome_colname,
    factor_weights_cols=compassion$factor_weights_cols,
    rowmeans_columns_list=compassion$rowmeans_columns_list,
    competency_cols_names=compassion$competency_cols_pattern,
    column_pattern_for_analyses=compassion$column_pattern_for_analyses,
    factor_weights_competency_cols=compassion$factor_weights_competency_cols,
    columns_to_remove_missing_values=compassion$columns_to_remove_missing_values,
    competency_cols_with_factor_weights=compassion$competency_cols_with_factor_weights)

})



```



