---
title: "BMK Data Processing for TRI/LARI Analyses"
author: "Sirish Shrestha"
date: "2023-04-28"
output: html_document
params: 
  data: NULL
  raters: !r c("Self", "Direct Report", "Peers", "Boss")
  required_cols: NULL
  competency_item_cols: NULL
  competency_cols: NULL
  research_cols: NULL
  grouping_cols: NULL
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```


```{r data-read, echo=FALSE}

df <- params$data
raters <- params$raters
grouping_cols <- params$grouping_cols
required_cols <- params$required_cols
competency_item_cols <- params$competency_item_cols
competency_cols <- params$competency_cols
research_cols <- params$research_cols

```


Pre-process the dataframe and aggregate the columns
```{r preprocess-df, echo=FALSE}

## get average item scores by rater
avg_scores_by_rater_df <- avg_scores_by_raters(df=df
                                          , required_cols=required_cols
                                          , item_cols=competency_item_cols
                                          , competency_cols=competency_cols
                                          , research_cols=research_cols
                                          , grouping_cols=grouping_cols)


## Filter the rows for all leaders with all required raters
avg_scores_by_rater_df <- filter_rows_with_all_raters(df=avg_scores_by_rater_df
                          , id_column = "ESI_Key"
                          , raters=raters
                          , rater_colname = c("RaterType"))



## Pivot the dataframe such that raters average scores are the columns
avg_scores_by_rater_df <- pivot_df(df=avg_scores_by_rater_df
                                 , var="RaterType"
                                 , id_column = "ESI_Key")


## set the clean dataframe as the current dataframe in the environment
set_current_df(df=avg_scores_by_rater_df)

```



```{r basic-missing-statistic, echo=FALSE}

count_missing_values(df=avg_scores_by_rater_df) %>%
  DT::datatable(filter = 'top', 
                style = "bootstrap4",
                class = "table table-striped table-bordered",
                options = list(paging = TRUE, 
                               pageLength = 10, 
                               autoWidth = TRUE),
                caption = htmltools::tags$caption(
                  style = 'caption-side: bottom; text-align: center;',
                  'Table 2: ', htmltools::em('Missing data count.'))) %>%
  DT::formatStyle(
    'Percentage',
    color = DT::styleInterval(0.70, c('green', 'red')),
  ) %>% 
  DT::formatPercentage(2) 


```

